app = "ophir-seller"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  SELLER_PORT = "8422"
  OPHIR_REGISTRY_URL = "https://ophir-registry.fly.dev"
  SELLER_ENDPOINT = "https://ophir-seller.fly.dev"

[[services]]
  internal_port = 8422
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = 15000
    grace_period = "30s"
    timeout = 5000
